### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [FFKL/s3cmd-zsh-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by FFKL** [comment]
@unixorn Hello! I'll add a license soon... with basic functionality of all options and commands to make plugin useful. It isn't finished yet. I am working on it now.

**Comment by unixorn** [comment]
Ok, close this when you're done and @ me and I'll add this to the list. Or you can make a PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), whatever is more convenient for you.

**Comment by FFKL** [comment]
@unixorn My [PR](https://github.com/unixorn/awesome-zsh-plugins/pull/1080)
